package com.aethyss.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors (safe contrast)
val md_theme_light_primary = Color(0xFF0066FF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF0B0B0B)
val md_theme_light_surface = Color(0xFFF6F7FB)
val md_theme_light_onSurface = Color(0xFF0B0B0B)
val md_theme_light_surfaceVariant = Color(0xFFE6E6E6)
val md_theme_light_onSurfaceVariant = Color(0xFF222222)
val md_theme_light_error = Color(0xFFB00020)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_outline = Color(0xFF9CA3AF)
val md_theme_light_inverseOnSurface = Color(0xFFF2F2F2)

// Dark theme colors (tested contrast)
val md_theme_dark_primary = Color(0xFF9ABDFF)
val md_theme_dark_onPrimary = Color(0xFF00294D)
val md_theme_dark_background = Color(0xFF0F1112)
val md_theme_dark_onBackground = Color(0xFFECEFF1)
val md_theme_dark_surface = Color(0xFF121314)
val md_theme_dark_onSurface = Color(0xFFECEFF1)
val md_theme_dark_surfaceVariant = Color(0xFF1D1F21)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC6CC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_outline = Color(0xFF3B3F44)
val md_theme_dark_inverseOnSurface = Color(0xFF0B0B0B)
